kind: pipeline
name: linux-amd64-sonarqube-scanner
type: vm

platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: pr tests
    image: plugins/docker:20
    commands:
      - echo "Running PR Tests in parallel"
    depends_on:
      - pr test java 11
      - pr test java 17
  - name: pr test java 11
    image: plugins/docker:20
    settings:
      daemon_off: false
      dockerfile: Dockerfile
      repo: plugins/sonarqube-scanner
      dry_run: true
  - name: pr test java 17
    image: plugins/docker:20
    settings:
      daemon_off: false
      dockerfile: DockerfileJava17
      repo: plugins/sonarqube-scanner
      dry_run: true
  # - name: publish
  #   image: plugins/docker:18
  #   settings:
  #     auto_tag: true
  #     auto_tag_suffix: linux-amd64
  #     daemon_off: false
  #     dockerfile: Dockerfile
  #     password:
  #       from_secret: docker_password
  #     repo: plugins/sonarqube-scanner
  #     username:
  #       from_secret: docker_username
  #   when:
  #     ref:
  #       - refs/heads/main
  #       - refs/tags/**
  - name: publish-2.0.2-java11
    image: plugins/docker:20
    settings:
      # auto_tag: true
      # auto_tag_suffix: v2.0.2-java11
      tags:
        - v2.0.2-java11
        - latest-java11
        - stable-java11
      daemon_off: false
      dockerfile: Dockerfile
      password:
        from_secret: docker_password
      repo: plugins/sonarqube-scanner
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
  - name: publish-2.0.2-java17
    image: plugins/docker:20
    settings:
      # auto_tag: true
      # auto_tag_suffix: v2.0.2-java17
      tags:
        - v2.0.2-java17
        - latest-java17
        - stable-java17
      daemon_off: false
      dockerfile: DockerfileJava17
      password:
        from_secret: docker_password
      repo: plugins/sonarqube-scanner
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"
    - "refs/pull/**"
