kind: pipeline
name: linux-amd64-sonarqube-scanner
platform:
  os: linux
  arch: amd64
steps:
- name: pr test
  image: plugins/docker:18
  settings:
    daemon_off: false
    dockerfile: Dockerfile
    repo: plugins/sonarqube-scanner
    dry_run: true
  when:
    event:
      - pull_request
- name: publish
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    daemon_off: false
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: plugins/sonarqube-scanner
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request
- name: publish-v1.0.5
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: v1.0.5
    daemon_off: false
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: plugins/sonarqube-scanner
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request
trigger:
  event:
  - push
